version: "3.9"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./auth-service:/app
    environment:
      - PORT=5000
    depends_on:
      - db

  grades-service:
    build: ./grades-service
    ports:
      - "5001:5001"
    volumes:
      - ./grades-service:/app
    environment:
      - PORT=5001
    depends_on:
      - db

  review-service:
    build: ./review-service
    ports:
      - "5002:5000"
    volumes:
      - ./review-service:/app
    environment:
      - PORT=5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clearsky
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
